src/components/toastr/overlay/overlay.ts
src/components/toastr/package.json
src/components/toastr/portal/dom-portal-host.ts
src/components/toastr/toastr-module.ts
src/components/toastr/toastr-service.ts
src/components/toastr/toastr.ts

this quiets the warning from rc5. Most of this was copied from material2.

use component factory resolver and add Toast to ngmodule

---

src/components/toastr/overlay/overlay-ref.ts
src/components/toastr/overlay/overlay.ts
src/components/toastr/portal/dom-portal-host.ts
src/components/toastr/portal/portal.ts
src/components/toastr/toast-component.ts
src/components/toastr/toastr-service.ts
src/demo-app/demo-app.html
src/index.html

changes from https://github.com/angular/material2/pull/1079

make overlays synchronous

---

src/lib/toast-component.ts

I don't know why it's here but it visually impacts the progress bar on my project, so I just get rid of it

remove "hello" text from toast-progress

---

README.md
src/app/app.module.ts
src/lib/toastr-config.ts
src/lib/toastr-module.ts
src/lib/toastr-service.ts

allow toastr options to be set from root

---

package.json
src/app/app.component.html
src/index.html
src/styles.scss
yarn.lock

fix missing classes
bump other packages

(demo) upgrade bootstrap alpha v6

---

src/lib/toastr.css

add "center center" positionClass .
Now, you can use "toastrConfig.positionClass = 'toast-center-center';" to set the toast's postion

add "center center" position

---

src/lib/toastr/toast-component.ts
src/lib/toastr/toastr-config.ts
src/lib/toastr/toastr-module.ts
src/lib/toastr/toastr-service.ts

This makes sure that DefaultConfig properly sets all values while still allowing the user to pick and choose which settings to override.

Start using partials for the interfaces

---

src/lib/toastr/toastr.service.ts

Use NgZone to run inside Angular's zone
fixes #275

Use NgZone to run inside Angular's zone

---

src/app/notyf.toast.ts
src/app/pink.toast.ts
src/lib/toastr/toast.component.ts

run setTimeout outside angular zone

---

e2e/app.e2e-spec.ts
e2e/app.po.ts

Tests for Pull-Request #299, as requested in #109

e2e(ngZone): test that toasts do not block protractor execution (#109)

---

src/app/home/home.component.spec.ts
src/lib/toastr/toastr.service.ts

fixes: ActiveToast.toastRef.componentInstance not being defined.
breaking change: ActiveToast takes a component type

fix: componentInstance not defined, ActiveToast component type

---

src/lib/toastr/toastr-config.ts

feat: leaves ontap open when tapToDismiss false #409

---

README.md
src/app/home/home.component.html
src/lib/toastr/default-config.ts
src/lib/toastr/toast-injector.ts
src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toast.component.ts
src/lib/toastr/toastr-config.ts
src/lib/toastr/toastr.service.ts

Add option to reset timout on duplicate (preventDuplicates must be enabled)
Requested in #416

Reset timeout on duplicate

---

src/lib/toastr-bs4-alert.scss

Fix bootstrap svg scss for IE

---

src/app/app.module.ts
src/app/home/home.component.html
src/app/home/home.component.ts
src/lib/overlay/overlay.ts
src/polyfills.ts
src/styles.scss

In addition to allowing dynamic inline containers, this updates the demo app to include inline as an option with multiple instances of `ToastContainerDirective`.

feat: Allows for dynamic inline containers

---

src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toast.component.ts
src/lib/toastr/toastr.service.ts

Fix resetTimeoutOnDuplicate #524 and remove unnecessary debug output #527

---

README.md
src/lib/toastr/toastr.service.ts

feat: return active toast if preventDuplicates is enabled (#550)

---

README.md

This adds an entry to FAQ list providing sample code snippet with tap
action handler.
Thanks!
closes #470

docs: Add sample of handling tap/click action. Closes #470

---

README.md

As per [this](https://stackoverflow.com/questions/59433831/how-to-hide-ngx-toaster-programmatically#59433859) question, there isn't any documentation about how to close or clear the toaster if `disableTimeOut` is set to `true`.

docs: Added useful functions description to the document

---

src/lib/toastr/toastr.service.ts

I did this change due to the issue here 
https://github.com/scttcper/ngx-toastr/issues/742
Please review it.
closes #742

feat(core): remove setTimeout, fixes maxOpened not preventing more toasts

---

README.md

formates the tables in readme.md

format readme table

---

src/lib/toastr/toastr-config.ts

Similar like ProgressAnimationType add a DisableTimoutType since it is not a simple type. This type can then be imported and used where it is declared/required in individual configuration.

fix: Declare type for DisableTimeOut configuration.

---

src/lib/toastr/toast.component.ts
src/lib/toastr/toastr-config.ts
src/lib/toastr/toastr.service.ts

relates #904 
Add generic to `payload` in `IndividualConfig` to enable stricter typing.

feat: Add generic for payload in IndividualConfig

---

src/lib/package.json

fix: Add ng-update entry to package.json
