package.json
rollup.js
stage-release.sh

Pull in rollup to create the toastr.umd.js file for compatibility with systemjs
Solves issues found in #41

Use rollup to build the toastr.umd.js file

---

src/lib/toastr-config.ts
src/lib/toastr-module.ts
src/lib/toastr-service.ts

This is to fix issues with angular >= 2.4.0 found in #44 and also simplifies the toastr-config.ts file by removing the interfaces and making the properties on the classes optional.
Not exactly sure why the interface GlobalToastConfig is causing issues but this seems to fix it.

Remove interfaces so that AoT works with angular >= 2.4.0

---

src/lib/toastr.css

The issue this pull request resolves is most visible when using the 'toast-top-center' positionClass. The toast-container overlay takes up the width of the screen and blocks any interaction with UI elements beneath it. See the following Plunker for an example:
http://plnkr.co/edit/EMoEzrtKvyOIfC2yoOct
Adding pointer-events style properties for _#toast-container_ and _.toast_ resolves the issues.

Fix toast-container overlay UI blocking

---

src/lib/overlay/overlay-ref.ts
src/lib/overlay/overlay.ts

this is wird ... the guys at [material2 use `_ngZone` just for bypassing async tests](https://github.com/angular/material2/blob/master/src/lib/core/overlay/overlay-ref.ts#L221-L226). since ngx-toastr has no backdrop, `_ngZone` seems to be an unused dependency.

refactor: remove un-used, transitive NgZone dependency

---

src/lib/toastr/toastr-config.ts

When setting iconClasses globally using forRoot(), iconClasses wasn't getting set properly.
This fixes #131

Fix iconClasses override when using forRoot()

---

src/lib/toastr/toast-component.ts

Sanitizing the html removes any potentially dangerous content, while still allowing safe html tags.  This is safer than just running `bypassSecurtiyTrustHtml`

Automatically sanitize HTML

---

README.md

This improves the flow of the readme a bit by grouping all mentions of individual and global options together. Also rearranges the individual options to come before global options since global options extends off of individual options.

Improve the flow of the readme

---

src/lib/toastr/default-config.ts
src/lib/toastr/toastr-service.ts

Overriding the global and individual configs was repetitive and a bit messy. This should greatly clean it up and make it more readable. Now both the global and individual configs use the same method to override the config.

Clean up config overrides

---

README.md
src/app/app.component.html
src/lib/toastr/default-config.ts
src/lib/toastr/toast-component.ts
src/lib/toastr/toastr-config.ts

This add support for the increasing progress bar requested in #192 
I'm not dead set on the new config property name. Any and all feedback is welcome.

Add support for increasing progress bar

---

src/app/notyf.toast.ts
src/app/pink.toast.ts
src/lib/toastr/toast-component.ts
src/lib/toastr/toastr-service.ts

closes #226
This would probably have to be a major version bump since it could break everyone extending the toast component. I'm also not sure that this is what we want. @yarrgh

switch to changedetectorref 

---

README.md
src/app/app.component.html
src/lib/toastr/default-config.ts
src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toast.component.ts
src/lib/toastr/toastr-config.ts

Convenience property that disables both `timeOut` and `extendedTimeOut` functionalities. 
Closes #282

feat: Add disableTimeOut configuration

---

src/lib/toastr/toast-noanimation.component.ts

ToastNoAnimation component wasn't being hidden when it was inactive. This caused the toasts opened with this component to be displayed when the `maxOpened` limit was reached even though they were 'inactive'.

fix: Apply proper style to ToastNoAnimation when inactive

---

src/lib/toastr/toastr-config.ts

Because of a copy-paste mistake the documented default for the number `extendedTimeOut` was the boolean value `false`, which made no sense.

Fix typo in JSDoc of extendedTimeOut

---

src/lib/package.json

Fix peerDependencies so that it doesn't error with `ng update`. `ng update` checks versions based on semver and doesn't like logical operators ('>', '>=', etc)
This is to address https://github.com/scttcper/ngx-toastr/issues/422#issuecomment-387701762

Fix peerDependencies

---

src/lib/toastr-bs4-alert.scss

There's missing styles for the close button. This doesn't show in the demo because the `button.toast-close-button` class is being applied somehow. That class comes from `toastr.css`
fixes #427

fix toastr-bs4-alert close button styling

---

src/lib/toastr/toastr-config.ts

The description for config properties was copied from `titleClass` to `messageClass` resulting in `messageClass` having a misleading description.
The wording in `titleClass` also had a "to" too much.

Fixes description for messageClass and titleClass

---

src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toastr.module.ts

Fix #542,  'Function calls are not supported in decorators' when using --prod build.
Related to https://github.com/angular/angular/issues/23609

Fix: Function calls are not supported in decorators' when using --prod build closes #542

---

src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toastr-config.ts
src/lib/toastr/toastr.module.ts
src/lib/toastr/toastr.service.ts

basically back to what we were doing in v8. because why change.
closes #543

fix(core): ensure toast default stays in ngmodule token

---

src/lib/toastr-bs4-alert.scss

Speaks for itself.
This fix is needed to be able to have 100% width.

fix: fixed forgotten .toast -> .ngx-toastr class name change

---

src/lib/toastr/toastr-config.ts

Changed toastClass property comment from `default: toast` to `default: ngx-toastr` to match v10.x changes.

docs(toastr-config): toastClass comment

---

package-lock.json
package.json
src/lib/toastr/toastr.service.ts

If you create two toasts with config
```
{
preventDuplicates: true,
countDuplicates: true,
resetTimeoutOnDuplicate: true,
timeOut: 0
}
```
the second one will cause the toast to be removed.
This happens because reset of timeout leads to setting hide-time to "now".
Hence, reset of timeout is prevented if there is no timeout at all.

feat: Prevent deletion of toasts if there are duplicates without timeout

---

src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toast.component.ts

When toast is create and is non visible this code puts inline style to tag element. Which is bad for 3th part overriding. 
I suggest to not return this  "inherit" and also "display" property to tag. And this will be control with css. 
[Code link](https://github.com/scttcper/ngx-toastr/commit/720af1ac29e5709ed67f890ce722a625dfb321c6#diff-b02c47a7f73543c1c90b62e0df13797bR82)

feat: change default style display behavior to nothing

---

README.md

cf. peerDependencies field for version 6.5.0 at https://registry.npmjs.org/ngx-toastr/

Set 6.5.0 as last version for Angular 4.X

---

src/lib/toastr/toast.component.ts

The issue that the condition is always truth when set disableTimeOut set to true, as `true` not equal to `'timeOut'`

fix: timeOut is not disabled by `disableTimeOut: true`

---

src/lib/toastr/toast-noanimation.component.ts

This issue fixes the warning I'm getting when using this package with Angular 9. 
Related issue: #583 
```
WARNING in Entry point 'ngx-toastr' contains deep imports into '/opt/colmena/kikstart/templates/kikstart-ui-starter/node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

fix: use correct location for import of ModuleWithProviders

---

README.md
src/app/home/home.component.html
src/lib/toastr/toastr-config.ts
src/lib/toastr/toastr.service.ts

As mentioned in #659 this PR based off #814 contains new global config to include title when checking for duplicates.
Tested locally that without config set, duplicates work as before 
Without includeTitleDuplicates: true
- Multiple duplicates with Title only, allows multiple toasts but stil counts duplicates.
- Multiple duplicates with Message only, wont allow duplicates but doesnt count.
- Two different titles with same message, picks up as duplcate and new title not shown as toast.
With includeTitleDuplicates: true
- Multiple duplicates with Title only, wont display duplicates and counts correctly
- Multiple duplicates with Message only, wont allow duplicates but still doesnt count.
- Two different titles with same message, no longer sees this as duplicate and new toast shown.
closes …

feat: Prevent title duplicates with `includeTitleDuplicates`

---

src/lib/toastr/toastr.service.ts

fix: Test if active before reducing number of active toasts #922

---

README.md
src/app/bootstrap.toast.ts
src/app/pink.toast.ts
src/lib/overlay/overlay-container.ts
src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toast.component.ts

Closes https://github.com/scttcper/ngx-toastr/issues/933, closes https://github.com/scttcper/ngx-toastr/issues/444, closes https://github.com/scttcper/ngx-toastr/issues/833
(note that I'm not too hot on angular per se, so this may need tweaking/correcting. In particular the change made to the README.md)

feat(accessibility): Move `aria-live=polite` to overlay container

---

src/lib/toastr/toast.component.ts

I'm not sure if this was intentional, if it was you can ignore/close this PR request
commit message: fix issue with mouseenter event clearing the timeout when disableTimeOut was set to extendedTimeOut
[Current behaviour](https://gyazo.com/7c1e544cb8b73b52f5db8d2a68b0d455) VS [New behaviour](https://gyazo.com/28d5e6fe4e2a276cb7d5ec17940985a4)

fix: extendedTimeOut and mouseenter event issue

---

README.md

Related to https://github.com/scttcper/ngx-toastr/issues/470 and https://github.com/scttcper/ngx-toastr/pull/598, this PR updates the documentation for how the reference of a specific toast can be used in conjunction with the event callback.
When I first implemented this library, it wasn't quite intuitive how this could be accomplished (as there the callback event is `void` instead of one with a payload).
I think the same problem (unclear how to accomplish) generated issues https://github.com/scttcper/ngx-toastr/issues/647 and https://github.com/scttcper/ngx-toastr/issues/408. So hopefully this PR makes it clear how it can be accomplished.

docs: update `onTap` doc to to use toast reference

---

README.md

This PR clarifies how multiple CSS classes can be added to customize styling.
Fixes https://github.com/scttcper/ngx-toastr/issues/594, which results from the same confusion.

doc: add clarify for adding custom CSS classes

---

src/app/app.module.ts
src/lib/overlay/overlay-container.ts
src/lib/overlay/overlay.ts
src/lib/public_api.ts
src/lib/toastr/toast-noanimation.component.ts
src/lib/toastr/toast.component.ts
src/lib/toastr/toast.directive.ts
src/lib/toastr/toast.provider.ts
src/lib/toastr/toastr.module.ts

Hello, 
I love this library and use it a lot, lately I've been using it in standalone apps, and always wrapped the ToastModule.forRoot in a custom provider function. 
I created this PR to easily use a provider function from the library itself, and also re-use it in the module providers, in order for this change to be backwards compatible. 
Also converted the components to standalone and also re-exported them from the modules for backwards compatibility. 
Fixes: #986, and I may also add readme changes for #968.

feat: added provider function, converted to standalone and used inject function

---

src/app/pink.toast.ts

I was making a custom toast component based off of the pink demo component, but the progress indicator was not showing.  The demo is missing the function call parenthesis!

docs: fix demo to show progress for pink toast

---

README.md

Readme is outdated, so we need to update section about ToastContainerModule

docs: Change readme section about ToastContainerModule to ToastContainerDirective
